feed/urls.py
from django.urls import path
from .views import HomePageView, AddPostView,PostDetailView
from . import views

app_name='feed'

urlpatterns=[
    path('', HomePageView.as_view(), name='index'),
    path('post/', AddPostView.as_view(), name='post'),
    path('detail/<int:pk>', views.PostDetailView.as_view(), name='detail'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from feed import urls as feed_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(feed_urls,namespace='Feed')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=40, blank=True, null=False)
    image = ImageField()
    description = models.TextField(blank=False, null=False)

    def __str__(self):
        return self.text

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=40)
    country = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']
    def __str__(self):
        return "Comment {} by {} ".format(self.body,self.name)


    

feed/forms.py
from .models import Comment
from django import forms

class PostForm(forms.Form):
    image = forms.FileField()
    text = forms.CharField(label="Name")
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Describe what does the image represents'}))

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'country', 'body')

feed/views.py
from typing import Any
from django import http
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm,CommentForm
from .models import Post,Comment
from django.shortcuts import redirect

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context
    
class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object, active=True)
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        # Handles the comment form submission
        post = self.get_object()
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        # If the form is invalid, reload the page with form errors
        return self.get(request, *args, **kwargs)  
    

class AddPostView(FormView):
    template_name= "new_post.html"
    form_class=PostForm
    success_url="/"

    def dispatch(self, request, *args, **kwargs) :
        self.request= request
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        new_object=Post.objects.create(
            text = form.cleaned_data['text'],
            image = form.cleaned_data['image'],
            description = form.cleaned_data['description']
        )
        messages.add_message(self.request, messages.SUCCESS, 'Your post was succesful')
        return super().form_valid(form)

   

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&family=Playfair+Display:ital@1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% include "navbar.html" %}

    {% if messages %}
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{message.tags}}{% else %}primary{% endif %} bg-gradient text-white text-center py-3">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container">
        {% block body %}sth here{% endblock %}
    </div>
    <script src="{% static 'script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% load social_share %}
{% block title %} Detail View {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
            <div class="col-10 py-4"> <h2> {{object.text}} </h2> </div>
                <div class="col-6"> 
                    <img src = "{{object.image.url}}" style='width:100%; height: auto;' class="py-2" >
                </div>
                <div class="col-4 ">
                    <h5 style="font-family: 'Oswald', sans-serif;"> {{object.description}} </h5>
                </div>
                <div class="container align-bottom">
                    <div class="row row-cols-4 py-4 text-center">
                    <div class="text-end"><div class="btn btn-warning disabled"> Share! &#128073; </div> </div>
                    <div class="col">{% post_to_facebook object.image.url "<svg xmlns='http://www.w3.org/2000/svg' width='36' height='36' fill='currentColor' class='bi bi-facebook' viewBox='0 0 16 16'><path d='M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z'/></svg>" %}</div>
                    <div class="col">{% post_to_whatsapp object.image.url "<svg xmlns='http://www.w3.org/2000/svg' class='text-success' width='36' height='36' fill='currentColor' class='bi bi-whatsapp' viewBox='0 0 16 16'><path d='M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z'/></svg>" %}</div>
                    <div class="col">{% post_to_twitter "Awesome pic: {{object.text}}. Check it out!" object.image.url "<svg xmlns='http://www.w3.org/2000/svg' width='36' height='36' fill='currentColor' class='bi bi-twitter' viewBox='0 0 16 16'><path d='M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z'/></svg>" %}</div>
                </div>
            </div>
        </div>
    </div>
    <button id="toggleComments" class="btn btn-info shadow-lg p-3 mb-5 bg-body rounded text-center">Show Comments </button>
    <div id="commentSection" class="comments_hidden py-3">
        <ul>
            {% for comment in comments %}
                <li>
                    <strong>{{ comment.name }}</strong> from {{ comment.country }} said:
                    <p>{{ comment.body }}</p>
                    <p>Posted on: {{ comment.created_on }}</p>
                </li>
            {% empty %}
                <li>No comments yet.</li>
            {% endfor %}
        </ul>
    <!-- Comment Form -->
        <h3>Add a Comment</h3>
        <form method="post" action="/detail/{{ post.pk }}">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">Submit Comment</button>
        </form>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block body %}
<div class="row">
    {% for post in posts %}
        <div class="col-sm-6 col-md-3 mt-4">
            <div class="card" style="width: 18rem;">
                {% thumbnail post.image "200x200" crop="center" as im %}
                    <img src="{{ im.url }}" class="card-img-top" alt="...">
                {% endthumbnail %}
                <div class="card-body">
                    <h5 class="card-title">{{post.text}}</h5>
                    <p class="card-text text-truncate" style="font-family: 'Playfair Display', serif;">{{post.description}}</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Detail</a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-sm-6 offset-3 text-center py-5 my-5">
            <h3> Welcome!</h3>
            <p> Add your first image? </p>
            <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success" > Upload Image </a> 
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">ImageShare</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'feed:post' %}">Add new Image</a>
                    </li>
                 </ul>
            </div>
        </div>
    </nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %} Upload an img {% endblock %}

{% block body %}
    <form method="post" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
    <h2>Upload a Photo! </h2>
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <button type="submit" class="btn btn-success btn-lg"> Submit Form </button>
    </div>
{% endblock %}